# SQLite version 3.x
#   gem install sqlite3
# development:
#   adapter: sqlite3
#   database: db/development.sqlite3
#   pool: 5
#   timeout: 5000

development:
  adapter: mysql2    
  database: aepm_production
  username: AETL
  password: ''
  host: 192.168.0.6
  port: 3306
  
test:
  adapter: mysql2
  database: aepm_test
  username: root
  password: 'AETL&*()7890'

production:
  adapter: mysql2    
  database: aepm_production
  username: AETL
  password: ''
  host: 192.168.0.6
  port: 3306